# File: build.yml

trigger:
- master

pool:
  name: Delphi build machine
  demands: Delphi_Rio_10_3_3

steps:
- powershell: |
    C:\Program Files (x86)\Embarcadero\Studio\20.0\bin\dcc32.exe ADLStoreLibrary4D_Console.dpr -UC:\Program Files (x86)\Embarcadero\Studio\20.0\lib -CC
    if (Test-Path -path ADLStoreLibrary4D_Console.exe) {
        .\ADLStoreLibrary4D_Console.exe
    }
  displayName: Build and run tests (Delphi Rio Update 3)